// <auto-generated />
using Discount.gRPC.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Discount.gRPC.Migrations
{
    [DbContext(typeof(DiscountContext))]
    [Migration("20260823040740_InitialCreateandSeed")]
    partial class InitialCreateandSeed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("Discount.gRPC.Models.Coupons", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Coupons");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 0m,
                            Description = "No discount on latest Pro model",
                            ProductName = "techphone 15 pro"
                        },
                        new
                        {
                            Id = 2,
                            Amount = 50m,
                            Description = "Standard model discount",
                            ProductName = "techphone 15"
                        },
                        new
                        {
                            Id = 3,
                            Amount = 0m,
                            Description = "No discount on premium flagship",
                            ProductName = "galaxy s24 ultra max"
                        },
                        new
                        {
                            Id = 4,
                            Amount = 75m,
                            Description = "Spring sale offer",
                            ProductName = "galaxy s24 standard"
                        },
                        new
                        {
                            Id = 5,
                            Amount = 100m,
                            Description = "AI camera special",
                            ProductName = "pixel pro 8"
                        },
                        new
                        {
                            Id = 6,
                            Amount = 80m,
                            Description = "Clearance discount",
                            ProductName = "pixel 8"
                        },
                        new
                        {
                            Id = 7,
                            Amount = 60m,
                            Description = "Flagship killer deal",
                            ProductName = "oneplus 12"
                        },
                        new
                        {
                            Id = 8,
                            Amount = 40m,
                            Description = "Mid-range special",
                            ProductName = "oneplus 12r"
                        },
                        new
                        {
                            Id = 9,
                            Amount = 90m,
                            Description = "Global release promo",
                            ProductName = "xiaomi 14 pro"
                        },
                        new
                        {
                            Id = 10,
                            Amount = 45m,
                            Description = "Edge series discount",
                            ProductName = "moto edge 50"
                        },
                        new
                        {
                            Id = 11,
                            Amount = 150m,
                            Description = "Creator bundle discount",
                            ProductName = "sony xperia 1 v"
                        },
                        new
                        {
                            Id = 12,
                            Amount = 120m,
                            Description = "Gamer mobile special",
                            ProductName = "asus rog phone 8"
                        },
                        new
                        {
                            Id = 13,
                            Amount = 0m,
                            Description = "No discount on limited edition",
                            ProductName = "nothing phone (2)"
                        },
                        new
                        {
                            Id = 14,
                            Amount = 20m,
                            Description = "Budget king offer",
                            ProductName = "poco x6 pro"
                        },
                        new
                        {
                            Id = 15,
                            Amount = 30m,
                            Description = "Speedster discount",
                            ProductName = "realme gt 5"
                        },
                        new
                        {
                            Id = 16,
                            Amount = 0m,
                            Description = "No discount on premium Mac",
                            ProductName = "macbook pro 16"
                        },
                        new
                        {
                            Id = 17,
                            Amount = 100m,
                            Description = "Student back-to-school discount",
                            ProductName = "macbook air 15"
                        },
                        new
                        {
                            Id = 18,
                            Amount = 150m,
                            Description = "Creator laptop sale",
                            ProductName = "dell xps 15"
                        },
                        new
                        {
                            Id = 19,
                            Amount = 200m,
                            Description = "Business fleet promo",
                            ProductName = "thinkpad x1 carbon"
                        },
                        new
                        {
                            Id = 20,
                            Amount = 80m,
                            Description = "Ultrabook deal",
                            ProductName = "asus zenbook 14"
                        },
                        new
                        {
                            Id = 21,
                            Amount = 120m,
                            Description = "Convertible laptop offer",
                            ProductName = "hp spectre x360"
                        },
                        new
                        {
                            Id = 22,
                            Amount = 0m,
                            Description = "No discount on premium gaming",
                            ProductName = "razer blade 16"
                        },
                        new
                        {
                            Id = 23,
                            Amount = 50m,
                            Description = "Holiday special discount",
                            ProductName = "acer swift go 14"
                        },
                        new
                        {
                            Id = 24,
                            Amount = 180m,
                            Description = "Esports gaming discount",
                            ProductName = "lenovo legion pro 7"
                        },
                        new
                        {
                            Id = 25,
                            Amount = 0m,
                            Description = "No discount on new release",
                            ProductName = "alienware m16 r2"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
